version: '2.2'

services:
  db:
    build:
      context: ../dockerfiles/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  app:
    build:
      context: ../dockerfiles/app
      args:
        - RAILS_ENV=production
    ports:
      - "3000:3333"
    volumes:
      - ../../:/var/www/app
      - bundle:/usr/local/bundle
      - os_log:/var/log
    init: true
    restart: always

volumes:
  db_data:
    driver: 'local'
  bundle:
    driver: 'local'
  os_log:
    driver: 'local'
