version: '3'

services:
  db:
    build:
      context: ../dockerfiles/db
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db_data:/var/lib/mysql

  app:
    build:
      context: ../dockerfiles/app
    ports:
      - "3333:3333"
    volumes:
      - ../../:/var/www/app:cached

  adminer:
    image: adminer:4.7
    ports:
      - 8333:8080

volumes:
  db_data:
    driver: 'local'
